# Generated by Django 4.2.2 on 2023-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='files',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='files/'),
        ),
    ]
